apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: shruti9023/flask-auth-devops:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_HOST
          value: flask-db.can8mcewqpr2.us-east-1.rds.amazonaws.com:3306
        - name: MYSQL_DB
          value: flaskdb
        - name: SECRET_KEY
          valueFrom:
              secretKeyRef:
                name: flask-secret
                key: SECRET_KEY
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
